<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="<?= SCRIPTS ?>css/style_connection.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <title>Login</title>
</head>

<body>
    <section class="section1">
        <div class="fblanc">
            <img class="logoModal " src="./public/assets/img/logo2.png" alt="Twitter">
            <div class="middle">
                <h2>Sign in to Twitter</h2>
                <button class="w-100 p-2 google mt-4"><i class="fa-brands fa-google"></i>Se Connecter avec Google</button>
                <button class="w-100 mt-3 p-2 apple"><i class="fa-brands fa-apple"></i>Se connecter avec Apple</button>
                <div class="ensemble">
                    <div class="height"></div>
                    <span class="hr">ou</span>
                    <div class="height"></div>
                </div>
                <form method="post">

                    <p class="form-floating">
                        <input class="w-100 ps-3 form-control" id="email" type=email name="email" placeholder="Email" required />
                        <label for="email">Email</label>
                    </p>
                    <p class="form-floating">
                        <input class="w-100 ps-3 form-control" id="password" type=password name="password" placeholder="Password" required />
                        <label for="password">Password</label>
                    <div class="Nextt">
                        <button class="Next">Se Connecter</button>
                    </div>
                </form>

                <div class="sign">
                    <span>Don't have an account? <a href="<?= BASE_NAME ?>register">Sign up</a></span>
                </div>
            </div>
            <div>

                <?php if (isset($_SESSION['errorLogin']) && strlen($_SESSION['errorLogin']) > 0) {
                    echo $_SESSION['errorLogin'];
                }
                ?>
            </div>
        </div>
    </section>
</body>

</html>
