<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Twitter</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
  <link rel="stylesheet" href="<?= SCRIPTS.'css'.DIRECTORY_SEPARATOR.'reset.css'?>">
  <link rel="stylesheet" href=" <?= SCRIPTS ?>/css/style_auth.css">
  <link rel="shortcut icon" href="<?= SCRIPTS ?>/assets/img/logo2.png">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body>
  <div class="row">
    <div class=" d-flex ">
      <div class="contenue col-lg-6 ">
        <img class="imglogo" src="<?= SCRIPTS ?>assets/img/logo.png" alt="logo de twitter le vrai, blanc">
      </div>

      <div class="contenair1 ">
        <img class="logo" src="<?= SCRIPTS ?>assets/img/logo2.png" alt="logo de twitter le vrai, blue">
        <span class="text">Ça se passe <br> maintenant</span>
        <span class="text2">Rejoignez Twitter dès aujourd'hui.</span>
        <section class="d-grid align-content-center">
        <button class="google"><i class="fa-brands fa-google"></i>Se Connecter avec Google</button>
              <button class="apple"><i class="fa-brands fa-apple"></i>Se connecter avec Apple</button> 
          <div class="d-flex ou justify-content-center align-items-center">
            <div class="height"></div>
            <span class="hr mr-2">ou</span>
            <div class="height"></div>
          </div>
          <span class="inscription"> <a class="text-decoration-none text-white ps-3" data-bs-toggle="modal" href="#myModal"> S'inscrire avec un numéro de téléphone ou une adresse email</a></span>

          <div class="modal fade" id="myModal">
            <div class="modal-dialog" id="width-modal">
              <div class="modal-content border-r">
                <div class="modal-header">
                  <div class="text-center w-100">
                    <img class="logoModal " src="./public/assets/img/logo2.png" alt="">
                  </div>
                </div>
                <div class="modal-body">
                  <form method="post" id="form">
                    <pre class="mb-3 h3 fw-bold">Creer votre compte</pre>
                    <div>
                      <div class="position-relative form-floating">
                        <input class="w-100 ps-3 form-control" id="input_Name" type=text name="Name_Lastname" maxlength="50" required />
                        <label for="input_Name">Name And Lastname</label>
                        <span id="span">50</span>
                      <pre id="Valid"></pre>
                      </div>
                      <div class="form-floating">
                        <input class="w-100 ps-3 form-control" id="input_Mail" type=email name="Email" placeholder="Email" required />
                        <label for="input_Mail">Email</label>
                        <pre id="Valid_Email"></pre>
                      </div>
                      <div class="form-floating">
                        <input class="w-100 ps-3 form-control" id="input_Password" type=password name="Password" placeholder="Password"  required />
                        <label for="input_Password">Password</label>
                        <!-- pattern="/^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*_=+-]).{8,12}$/g" -->
                      </div>
                    </div>
                    <div class="d-flex flex-column mb-4">
                      <span>Date de Naissance</span>
                      <span>Cette information ne sera pas affichée publiquement. Confirmez votre âge, même si ce compte est pour une entreprise, un animal de compagnie ou autre chose.</span>
                    </div>
                    <div class="d-flex justify-content-between">
                      <select name="mois" id="mois" required>
                      <option value="">Mois</option>
                        <?php
                        $mois = array(
                          1 => 'Janvier', 2 => 'Février', 3 => 'Mars',
                          4 => 'Avril', 5 => 'Mai', 6 => 'Juin',
                          7 => 'Juillet', 8 => 'Aout', 9 => 'Septembre',
                          10 => 'Octobre', 11 => 'Novembre', 12 => 'Decembre'
                        );

                        foreach ($mois as $key => $moi) {
                          echo '<option value="' . $key . '">' . $moi . '</option>';
                        }
                        ?>
                      </select>
                      

                  

                      <select name="jour" id="jour" required>
                      <option value="">Jour</option>
                        <?php
                        for ($date_jour = 1; $date_jour <= 31; $date_jour++) {
                        ?>
                          <option value="<?php echo $date_jour ?>"><?php echo $date_jour ?></option>
                        <?php
                        }
                        ?>
                      </select>


                      <select name="annee" id="annee" required>
                        <option value="">Année</option>
                        <?php
                        for ($date_annee = 2022; $date_annee >= 1902; $date_annee--) {
                        ?>
                          <option value="<?php echo $date_annee ?>"><?php echo $date_annee ?></option>
                        <?php
                        }
                        ?>
                      </select>
                    </div>
                    <p>
                      <button class="boutton w-100 p-2 rounded-pill mt-5 border border-1" type="submit" id="Validate">Valider</button>
                    </p>
                  </form>
                </div>
              </div>
            </div>
          </div>


          <div class="condition">En vous inscrivant, vous acceptez les <a class="text-decoration-none" href="#">Conditions d'Utilisation</a> et la <a class="text-decoration-none" href="#">Politique de Confidentialité</a> , incluant <a class="text-decoration-none" href="#"> l'Utilisation de Cookies</a>.</div>
          <div class="compte"> Vous avez déjà un compte?</div> 
          <div class="connection"> <a class="text-decoration-none text-black" href="<?= BASE_NAME ?>login">Se Connecter</a> </div>
        </section>
      </div>
    </div>
  </div>
  <div class="contenue2 d-lg-none ">
  <img class="imglogo2" src="./public/assets/img/logo.png" alt="logo de twitter le vrai, blanc">
  </div>
  <footer>
    <div class="d-flex justify-content-center flex-wrap mt-3">
      <a class="lien" href="#">À propos</a>
      <a class="lien" href="#">Centre d'assistance</a>
      <a class="lien" href="#">Conditions d’utilisation</a>
      <a class="lien" href="#">Politique de Confidentialité</a>
      <a class="lien" href="#">Politique relative aux cookies</a>
      <a class="lien" href="#">Accessibilité</a>
      <a class="lien" href="#">Informations sur les publicités</a>
      <a class="lien" href="#">Blog</a>
      <a class="lien" href="#">Statut</a>
      <a class="lien" href="#">Carrières</a>
      <a class="lien" href="#">Ressources de la marque</a>
      <a class="lien" href="#">Publicité</a>
      <a class="lien" href="#">Marketing</a>
      <a class="lien" href="#">Twitter pour les professionnels</a>
      <a class="lien" href="#">Développeurs</a>
      <a class="lien" href="#">Répertoire</a>
      <a class="lien" href="#">Paramètres</a>
      <a class="lien" href="#"> © 2022 Twitter, Inc.</a>
    </div>
  </footer>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
  <script src="<?= SCRIPTS ?>js/auth.js"></script>
</body>

</html>