<?php
if(isset($_SESSION['username']) && !empty($_SESSION['username'])){
    $username = $_SESSION['username'];
    $username = substr($username, 1);
    $name = $_SESSION['name'];
    $user_id = $_SESSION['user_id'];
}
else{
    $username = '';
}
?>
<!-- ?php var_dump($params['ramdomFollow'])?> -->
<!DOCTYPE html>
<html lang="fr">
<head>
    <!-- DEFAULT META TAGS -->
    <meta charset="UTF-8">
    <meta name="shortcutviewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel=" icon" type="image/png" href="<?= SCRIPTS.'img'.DIRECTORY_SEPARATOR.'favicon.ico'?>"/>
    <?php if(isset($params['titrepage'])) : ?>
        <title><?= $params['titrepage'] ?> - Twitter</title>
        <?php else :?>
        <title>Twitter</title>
    <?php endif ?>
 
       <meta name="author" content="Mamady Madjid Tene cheikh">
       <link rel="icon" href="<?= SCRIPTS.'assets'.DIRECTORY_SEPARATOR.'favicon.ico'?>">
       <!-- fontawesome && ionicons-->
       <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
       <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js" defer></script>
     <!-- bootstrap -->
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
     <!-- css -->
    <link rel="stylesheet" href="<?= SCRIPTS.'css'.DIRECTORY_SEPARATOR.'reset.css'?>">
    <link rel="stylesheet" href="<?= SCRIPTS.'css'.DIRECTORY_SEPARATOR.'variables.css'?>">
    <link rel="stylesheet" href="<?= SCRIPTS.'css'.DIRECTORY_SEPARATOR.'style.css'?>">
    <?php if(isset($params['css'])) : ?>
      <link rel="stylesheet" href="<?= SCRIPTS.'css'.DIRECTORY_SEPARATOR.$params['css']?>">
    <?php endif ?>

    <link rel="stylesheet" media="screen and (max-width: 500px)" href="<?= SCRIPTS.'css'.DIRECTORY_SEPARATOR.'navbarMobile.css'?>">
    <link rel="stylesheet" media="screen and (min-width: 501px)" href="<?= SCRIPTS.'css'.DIRECTORY_SEPARATOR.'navbar.css'?>">
</head>
<body>
    
<header>
        <div class="navHeader containerMobileNav">
          <div class="header__left" id="avatar">
              <div class="avatar"></div>
          </div>
          <div class="header__center">
              <h2 aria-level="2" role="heading"> <span class="header__title">Home</span></h2>
          </div>
          <div class="hearder__right">
              <div class="hearder__right--icon">
                  <svg viewBox="0 0 24 24" aria-hidden="true"><g><path d="M22.772 10.506l-5.618-2.192-2.16-6.5c-.102-.307-.39-.514-.712-.514s-.61.207-.712.513l-2.16 6.5-5.62 2.192c-.287.112-.477.39-.477.7s.19.585.478.698l5.62 2.192 2.16 6.5c.102.306.39.513.712.513s.61-.207.712-.513l2.16-6.5 5.62-2.192c.287-.112.477-.39.477-.7s-.19-.585-.478-.697zm-6.49 2.32c-.208.08-.37.25-.44.46l-1.56 4.695-1.56-4.693c-.07-.21-.23-.38-.438-.462l-4.155-1.62 4.154-1.622c.208-.08.37-.25.44-.462l1.56-4.693 1.56 4.694c.07.212.23.382.438.463l4.155 1.62-4.155 1.622zM6.663 3.812h-1.88V2.05c0-.414-.337-.75-.75-.75s-.75.336-.75.75v1.762H1.5c-.414 0-.75.336-.75.75s.336.75.75.75h1.782v1.762c0 .414.336.75.75.75s.75-.336.75-.75V5.312h1.88c.415 0 .75-.336.75-.75s-.335-.75-.75-.75zm2.535 15.622h-1.1v-1.016c0-.414-.335-.75-.75-.75s-.75.336-.75.75v1.016H5.57c-.414 0-.75.336-.75.75s.336.75.75.75H6.6v1.016c0 .414.335.75.75.75s.75-.336.75-.75v-1.016h1.098c.414 0 .75-.336.75-.75s-.336-.75-.75-.75z"></path></g></svg>
              </div>
          </div>
        </div>

        <div class="containereSideBarLeft containere">
              <div class="side-barr">
                    <ul class="nav-barr">
                         <li class="nav-bar-brandd mob"><a href="<?= BASE_NAME ?>"><ion-icon name="logo-twitter"></ion-icon></a></li>
                         <li class="navi-item navo"><a href="<?= BASE_NAME ?>" class="item-iconn homee"><ion-icon name="home-outline"></ion-icon></a><a href="<?= BASE_NAME ?>" class="item-linkk">Home</a> </li>
                      <li class="navi-item hash"><a href="<?= BASE_NAME ?>" class="item-iconn hash"><span>#</span></a><a href="#" class="item-linkk">Explorer</a> </li>
                      <li class="navi-item navo"><a href="<?= BASE_NAME ?>" class="item-iconn"><ion-icon name="notifications-outline"></ion-icon></a><a href="#" class="item-linkk">Notifications</a> </li>
                      <li class="navi-item navo"><a href="<?= BASE_NAME ?>" class="item-iconn"><ion-icon name="mail-outline"></ion-icon></a><a href="#" class="item-linkk">Messages</a> </li>
                      <li class="navi-item mob"><a href="<?= BASE_NAME ?>" class="item-iconn"><ion-icon name="bookmark-outline"></ion-icon></a><a href="#" class="item-linkk">Signets</a> </li>
                      <li class="navi-item mob"><a href="<?= BASE_NAME ?>" class="item-iconn"><ion-icon name="reader-outline"></ion-icon></a><a href="#" class="item-linkk">Listes</a> </li>
                      <li class="navi-item mob"><a href="<?= BASE_NAME.$username?>" class="item-iconn"><ion-icon name="person-outline"></ion-icon></a><a href="<?= BASE_NAME.$username?>" class="item-linkk">Profile</a> </li>
                      <li class="navi-item mob" id="moreBtn"><a href="#" class="item-iconn" ><ion-icon name="ellipsis-horizontal-circle-outline"></ion-icon></a><a href="#" class="item-linkk">Plus</a> </li>
                      <a href="#" class="tweet-btnn mob"><ion-icon name="pencil-outline"></ion-icon> <div class="text">Tweet</div></a>

                      <div class="sub-items-boxx">
                          <ul>
                               <li class="sub-itemm">
                                   <a href="#" class="item-iconn"><ion-icon name="chatbubble-ellipses-outline"></ion-icon></a><a href="#" class="item-linkk">Topic</a>
                               </li>

                              <li class="sub-itemm">
                                  <a href="#" class="item-iconn"><ion-icon name="flash-outline"></ion-icon></a><a href="#" class="item-linkk">Moments</a>
                              </li>

                            <li class="sub-itemm">
                              <a href="#" class="item-iconn"><ion-icon name="newspaper-outline"></ion-icon></a><a href="#" class="item-linkk">Newsletter</a>
                            </li>

                            <li class="sub-itemm">
                              <a href="#" class="item-iconn"><ion-icon name="rocket-outline"></ion-icon></a><a href="#" class="item-linkk">Twitter for pro</a>
                            </li>

                            <li class="sub-itemm">
                              <a href="#" class="item-iconn"><ion-icon name="chatbubble-ellipses-outline"></ion-icon></a><a href="#" class="item-linkk">Twetter Ads</a>
                            </li>

                            <li class="sub-itemm">
                              <a href="#" class="item-iconn"><ion-icon name="chatbubble-ellipses-outline"></ion-icon></a><a href="#" class="item-linkk">Topic</a>
                            </li>

                            <li class="sub-itemm">
                              <a href="#" class="item-iconn"><ion-icon name="stats-chart-outline"></ion-icon></a><a href="#" class="item-linkk">Analytics</a>
                            </li>

                               <ul class="configg">
                                 <li class="sub-itemm">
                                   <a href="#" class="item-iconn"><ion-icon name="settings-outline"></ion-icon></a><a href="#" class="item-linkk">Settings</a>
                                 </li>

                                 <li class="sub-itemm">
                                   <a href="#" class="item-iconn"><ion-icon name="help-circle-outline"></ion-icon></a><a href="#" class="item-linkk">Help Center</a>
                                 </li>

                                 <li class="sub-itemm">
                                   <a href="#" class="item-iconn"><ion-icon name="color-palette-outline"></ion-icon></a><a href="<?= BASE_NAME ?>display" class="item-linkk">Display</a>
                                 </li>

                                 <li class="sub-itemm">
                                   <a href="#" class="item-iconn"><ion-icon name="power-outline"></ion-icon></a><a href="<?= BASE_NAME ?>logout" class="item-linkk">Log out</a>
                                 </li>
                               </ul>
                          </ul>
                      </div>
                    </ul>
                    <a href="#" class="profile-btnn">
                      <div class="profile-infoo">
                           <img src="<?= SCRIPTS ?>assets/Profile_IMG/5f41b81d5705e.jpeg" class="profile-imggg" width="35px" height="35px">
                        <div>
                          <p class="nameee"><?=$name?></p>
                          <p class="usernamee">@<?=$username?></p>
                        </div>
                      </div>
                      <div class="option-iconn">
                        <ion-icon name="ellipsis-horizontal-outline"></ion-icon>
                      </div>
                    </a>
              </div>
              <div class="overlay">

              </div>

        </div>
</header>

    <div class="navbarBottom containerMobileNav">
        <nav>
            <a href="<?= BASE_NAME ?>" title="Home" aria-label="Home" class="item-iconn"><ion-icon name="home-outline"></ion-icon></a>
            <a href="<?= BASE_NAME ?>search" title="search" aria-label="search" class="item-iconn"><ion-icon name="search-outline"></ion-icon></a>
            <a href="#" title="notifications" aria-label="notifications" class="item-iconn"><ion-icon name="notifications-outline"></ion-icon></a>
            <a href="#" title="mail" aria-label="mail" class="item-iconn"><ion-icon name="mail-outline"></ion-icon></a>
        </nav>
    </div>

    <div class="modalAccount containerMobileNav">
        <div class="modalAccount__title">
            <h2 aria-level="2" role="heading"> <span class="header__title">Account info</span></h2>
            <button type="button" id="removeModalAccount" aria-label="Close" role="button" class="item-iconn btn"><ion-icon name="close-outline"></ion-icon></button>
        </div>
        <div class="modalAccount__account">
            <div class="avatar"></div>
            <div class="btn btnAdd item-iconn">
                <ion-icon name="add-outline"></ion-icon>
            </div>
        </div>
        <div class="modalAccount__info">
           <div class="modalAccount__info--user">
               <h3 class="modalAccount__info-fullname"><?=$name?></h3>
               <h3 class="modalAccount__info-username"><?=$username?></h3>
           </div>
              <div class="modalAccount__info--follow">
                <a href="#" role="link"> <span>0</span> Following </a>
                <a href="#" role="link"> <span>0</span> Followers </a>
              </div>
        </div>
        <nav class="modalAccount__nav containerMobileNav">
            <a href="<?= BASE_NAME.$username?>" title="Profile" aria-label="Profile" class="item-iconn"><ion-icon name="person-outline"></ion-icon> <span>Profile</span> </a>
            <a href="#" title="List" aria-label="List" class="item-iconn"><ion-icon name="list-outline"></ion-icon> <span>List</span></a>
            <a href="#" title="Topic" aria-label="Topic" class="item-iconn"><ion-icon name="chatbubble-ellipses-outline"></ion-icon> <span>Topic</span></a>
            <a href="#" title="Bookmarks" aria-label="Bookmarks" class="item-iconn"><ion-icon name="book-outline"></ion-icon> <span>Bookmarks</span></a>
            <a href="#" title="Moments" aria-label="Moments" class="item-iconn"><ion-icon name="flash-outline"></ion-icon> <span>Moments</span></a>
            <a href="#" title="Newsletter" aria-label="Newsletter" class="item-iconn"><ion-icon name="newspaper-outline"></ion-icon> <span>Newsletter</span></a>
            <a href="<?= BASE_NAME ?>display" title="Display" aria-label="Display" class="item-iconn"><ion-icon name="color-palette-outline"></ion-icon> <span>Display</span></a>
            <a href="#" title="Settings" aria-label="Settings" class="item-iconn"><ion-icon name="settings-outline"></ion-icon> <span>Settings</span></a>
            <a href="<?= BASE_NAME ?>logout" title="Log out" aria-label="Settings" class="item-iconn"><ion-icon name="power-outline"></ion-icon> <span>Log out</span></a>
        </nav>
   
    </div>
    
    <aside class="aside__btnTweet containerMobileNav">
        <a href="#" class="tweet-btn"> <svg viewBox="0 0 24 24" aria-hidden="true" class="r-lrvibr r-19tjxh9"><g><path d="M8.8 7.2H5.6V3.9c0-.4-.3-.8-.8-.8s-.7.4-.7.8v3.3H.8c-.4 0-.8.3-.8.8s.3.8.8.8h3.3v3.3c0 .4.3.8.8.8s.8-.3.8-.8V8.7H9c.4 0 .8-.3.8-.8s-.5-.7-1-.7zm15-4.9v-.1h-.1c-.1 0-9.2 1.2-14.4 11.7-3.8 7.6-3.6 9.9-3.3 9.9.3.1 3.4-6.5 6.7-9.2 5.2-1.1 6.6-3.6 6.6-3.6s-1.5.2-2.1.2c-.8 0-1.4-.2-1.7-.3 1.3-1.2 2.4-1.5 3.5-1.7.9-.2 1.8-.4 3-1.2 2.2-1.6 1.9-5.5 1.8-5.7z"></path></g></svg></a>
    </aside>
   
    <main class="tout">
        <div class="MainContainer">
        <?= $content ?>
        </div>

        <div class="Right">
          <?php if(isset($_GET['url']) && $_GET['url'] != "search"){ ?>
              <div class="SearchBar">
                    <div class="logocherche item-iconn">
                      <ion-icon name="search-outline"></ion-icon>
                    </div>
                    <div class="searchInputDiv">
                      <form id="formSearch">
                      <input type="text" id="search" name="q" class="Look" placeholder="Search Twitter" autocomplete="off">
                      </form>
                    </div>
                    <div class="cancelSearch item-iconn">
                      <ion-icon name="close-circle"></ion-icon>
                    </div>
              </div>
          <?php } ?>
              <div class="TrendContain">
                  <div class="trendTitle">
                        <h2>Trends for you</h2>
                  </div>
                  <ul class="TrendList">
      
                        <li class="TrendItem">
                          <p class="SujetType">Music</p>
                         <a href="<?=BASE_NAME.'search?q=%23mamady'?>">#mamady</a>
                          <p class="NumTweet">19K tweets</p>
                        </li>
                        <li class="TrendItem">
                          <p class="SujetType">Music</p>
                            <a href="#">#Donda2</a>
                          <p class="NumTweet">19K tweets</p>
                        </li>
                    <li class="TrendItem">
                      <p class="SujetType">Music</p>
                      <a href="<?=BASE_NAME.'search?q=%23onepiece'?>">#onepiece</a>
                      <p class="NumTweet">19K tweets</p>
                    </li>
                    <li class="TrendItem">
                      <p class="SujetType">Music</p>
                      <a href="<?=BASE_NAME.'search?q=%23carre'?>">#carre</a>
                      <p class="NumTweet">19K tweets</p>
                    </li>
                    <li class="TrendItem">
                      <p class="SujetType">Music</p>
                      <a href="<?=BASE_NAME.'search?q=%23test'?>">#test</a>
                      <p class="NumTweet">19K tweets</p>
                    </li>
                  </ul>
                <div class="showMore">
                  <a class="moreofmore" href="#">show more</a>
                </div>
              </div>
              <div class="Qui">
                    <div class="hos">
                        <h2 class="titleWhoToFollow">Who to follow</h2>
                    </div>
                    <div class="listWhoToFollow">
                          <ul class="Follow">
                            <!-- ?php var_dump($params['ramdomFollow']); ?> -->
                          <?php foreach($params['ramdomFollow'] as $ramdomFollow): ?>
                              <li class="FollowItem"><div class="profile-info">
                                <img class="profile-imggg" height="35px" src="<?= SCRIPTS .'assets/'?><?=$ramdomFollow->avatar ?? 'Profile_IMG/5f41b81d5705e.jpeg'?>" width="35px">
                                <div class="redirctProfile">
                                  <p class="name"><?=$ramdomFollow->name ?? 'profile'?></p>
                                  <p class="username"><?=$ramdomFollow->username ?? 'profile'?></p>
                                </div>
                                <div class="bouttonFollow">
                                  <button class="Followw userIs-Follow" data-follow="<?=$ramdomFollow->id?>" data-user="<?=$user_id?>">Follow</button>
                                </div>
                               </div>
                               </li>
                               <?php endforeach; ?>
                          </ul>
                    </div>
                <div class="showMore">
                  <a class="moreofmore" href="#">show more</a>
                </div>
              </div>
        </div>
    </main>    

     <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    <!--js  --> 
    <script src="<?= SCRIPTS.'js'.DIRECTORY_SEPARATOR.'navbar.js'?>"></script>   
    <script src="<?= SCRIPTS.'js'.DIRECTORY_SEPARATOR.'main.js'?>"></script>  
    <?php if(isset($_GET['url']) && $_GET['url'] != "search"){ ?>
    <script src="<?= SCRIPTS.'js'.DIRECTORY_SEPARATOR.'searchbar.js'?>"></script> 
    <?php } ?>

    <?php if(isset($params['js'])) : ?>
      <script src="<?= SCRIPTS.'js'.DIRECTORY_SEPARATOR.$params['js']?>"></script> 
    <?php endif ?>
    
</body>

</html>