<h1>Edit Profile</h1>

<form>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputEmail4">Email</label>
      <input type="email" class="form-control" id="inputEmail4" placeholder="Email">
    </div>
    <div class="form-group col-md-6">
      <label for="inputPassword4">Password</label>
      <input type="password" class="form-control" id="inputPassword4" placeholder="Password">
    </div>
  </div>
  <div class="form-group">
    <label for="inputAddress">Address</label>
    <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
  </div>
  <div class="form-group">
    <label for="inputAddress2">Address 2</label>
    <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputCity">City</label>
      <input type="text" class="form-control" id="inputCity">
    </div>
    <div class="form-group col-md-4">
      <label for="inputState">State</label>
      <select id="inputState" class="form-control">
        <option selected>Choose...</option>
        <option>...</option>
      </select>
    </div>
    <div class="form-group col-md-2">
      <label for="inputZip">Zip</label>
      <input type="text" class="form-control" id="inputZip">
    </div>
  </div>
  <div class="form-group">
    <div class="form-check">
      <input class="form-check-input" type="checkbox" id="gridCheck">
      <label class="form-check-label" for="gridCheck">
        Check me out
      </label>
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Sign in</button>
</form>

<!-- <div class="col-lg-12">
    <div class="table-responsive"> 
        <table class="table table-bordered mt-4 mb-50">
            <thead class="thead-dark">
                <tr>
                <th scope="col" class="h4 text-center">#</th>
                <th scope="col" class="h4 text-center ">prenom</th>
                <th scope="col" class="h4 text-center">date de naissance</th>
                <th scope="col" class="h4 text-center">nom</th>
                <th scope="col" class="h4 text-center">email</th>
                <th scope="col" class="h4 text-center">passWORD</th>
                <th scope="col" class="h4 text-center">genre</th>
                <th scope="col" class="h4 text-center">ville</th>
                <th scope="col" class="h4 text-center">pays</th>
                <th scope="col" class="h4 text-center">loisir</th>
                </tr>
            </thead>
            <tbody>
            <form method="post" >
            !-- ?php foreach($params['user'] as $user):?> -->
                <!-- <tr> -->
                <!-- <th scope="row" class="h4 text-center">
                <input type="text" name="firstname" value="?= htmlspecialchars($user) ?>">
                </th> -->
                <!-- </tr> -->
                <!-- ?php endforeach ?>  -->

                    <!-- <div class="validerAd">
                        <button type="submit" name="divers_2" class="btn btn-success">Valider</button>
                    </div> -->
<!-- 
                </form>
            </tbody>
        </table>
    </div>
</div> --> -->
