<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>ERROR 404</title>
	<link rel="icon" href="<?= SCRIPTS.'assets'.DIRECTORY_SEPARATOR.'favicon.ico'?>">
	<link rel="stylesheet" href="<?= SCRIPTS.'css'.DIRECTORY_SEPARATOR.'error404.css'?>">
</head>
<body>
<div class="container-error404">
<section class="error404">
<div class="message">
	<p class="rotate">ERROR</p>
	<h1 class="errorChiffe">404</h1>
</div>
</section>

</div>
</body>
</html>


