<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Display</title>
    <link rel="icon" href="<?= SCRIPTS.'assets'.DIRECTORY_SEPARATOR.'favicon.ico'?>">
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js" defer></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="<?= SCRIPTS.'css'.DIRECTORY_SEPARATOR.'display.css'?>">
    <script src="<?= SCRIPTS.'js'.DIRECTORY_SEPARATOR.'main.js'?>" defer></script>
</head>
<body>
    <div class="contenaireDisplay">
    <header>
            <button id="arrowBack" class="item-iconn btn"><ion-icon name="arrow-back-outline"></ion-icon></button>
            <h2 class="title">Customize your view</h2>
    </header>

    <main>
        <div class="DisplayTextView">
            <p>Manage your font size, color, and background. These settings affect all the Twitter accounts on this browser.</p>
        </div>
        <div class="displayTweet">
            <div class="displayTweet__img">
                <div class="displayTweet__img--logo">
            
                </div>
                <!-- <img src="<?= SCRIPTS.'assets'.DIRECTORY_SEPARATOR.'img'.DIRECTORY_SEPARATOR.'logo2.png'?>" alt="tweet img"> -->
            </div>
            <div class="displayTweet__content">
                <div class="displayTweet__content__name">
                    <p><span class="">@Twitter <svg class="certificate" viewBox="0 0 24 24" aria-label="Verified account"><g><path d="M22.5 12.5c0-1.58-.875-2.95-2.148-3.6.154-.435.238-.905.238-1.4 0-2.21-1.71-3.998-3.818-3.998-.47 0-.92.084-1.336.25C14.818 2.415 13.51 1.5 12 1.5s-2.816.917-3.437 2.25c-.415-.165-.866-.25-1.336-.25-2.11 0-3.818 1.79-3.818 4 0 .494.083.964.237 1.4-1.272.65-2.147 2.018-2.147 3.6 0 1.495.782 2.798 1.942 3.486-.02.17-.032.34-.032.514 0 2.21 1.708 4 3.818 4 .47 0 .92-.086 1.335-.25.62 1.334 1.926 2.25 3.437 2.25 1.512 0 2.818-.916 3.437-2.25.415.163.865.248 1.336.248 2.11 0 3.818-1.79 3.818-4 0-.174-.012-.344-.033-.513 1.158-.687 1.943-1.99 1.943-3.484zm-6.616-3.334l-4.334 6.5c-.145.217-.382.334-.625.334-.143 0-.288-.04-.416-.126l-.115-.094-2.415-2.415c-.293-.293-.293-.768 0-1.06s.768-.294 1.06 0l1.77 1.767 3.825-5.74c.23-.345.696-.436 1.04-.207.346.23.44.696.21 1.04z"></path></g></svg></span class="bg-secondary">@Twitter · 55m</span></p>
                </div>
                <div class="displayTweet__content__text">
                    <p>Lorempisicing elit. Quisquam, quidem Lorem ipsum, dolor sit riufrurvo rff golllzezh sed ratione minima dolores, libero deserunt! <span>@Twitter</span>.</p>
                </div>
            </div>
        </div>

        <h3 class="palettecolor__title">Font Size</h3>
        <div class="chooseSize">
            <div class="chooseSize_aa">aA</div>
            <div class="chooseSize__range">
                <div class="chooseSize__range__line">
                    <div class="chooseSize__range__circle" data-size="1.2rem" data-pos="1"></div>
                    <div class="chooseSize__range__circle" data-size="1.4rem" data-pos="25"></div>
                    <div class="chooseSize__range__circle current" data-size="1.7rem" data-pos="50"></div>
                    <div class="chooseSize__range__circle" data-size="1.85rem" data-pos="75"></div>
                    <div class="chooseSize__range__circle" data-size="2rem" data-pos="94"></div>
                </div>
            </div>
            <div class="chooseSize_aa">Aa</div>
        </div>
        <h3 class="palettecolor__title"> Color</h3>
        <div class="chooseColor">
           
                 <div class="chooseColor__color"> <div class="chooseColor__item" data-color="#1D9BF0"><ion-icon name="checkmark-outline"></ion-icon></div></div>
                 <div class="chooseColor__color"> <div class="chooseColor__item" data-color="#FED404"></div></div>
                 <div class="chooseColor__color"><div class="chooseColor__item" data-color="#F81880"></div></div>
                 <div class="chooseColor__color"><div class="chooseColor__item" data-color="#7856ff"></div></div>
                 <div class="chooseColor__color"><div class="chooseColor__item" data-color="#FA7A02"></div></div>
                 <div class="chooseColor__color"> <div class="chooseColor__item" data-color="#30BA7C"></div></div>
        </div>
        <h3 class="palettecolor__title"> Color</h3>
        <div class="chooseBackground">
                <div aria-label="Light" class="chooseBackground__item bdr-primary" data-background="rgb(255,255,255)"> 
                    <div class="chooseBackground__radio bg"><ion-icon name="checkmark-outline"></ion-icon></div>
                   <h4 class="chooseBackground__title">Default</h4>
                </div>
           
            <div aria-label="Dim" class="chooseBackground__item" data-background="rgb(21, 32, 43)"> 
                <div class="chooseBackground__radio"></div>
                <h4 class="chooseBackground__title">Dim</h4>
            </div>
            <div aria-label="Dark" class="chooseBackground__item" data-background="rgb(0,0,0)"> 
                <div class="chooseBackground__radio"></div>
                <h4 class="chooseBackground__title">Dark</h4>
            </div>
        </div>
    </main>
    </div>
    <script src="<?= SCRIPTS.'js'.DIRECTORY_SEPARATOR.'display.js'?>"></script>
</body>
</html>